name: Composer CI
on: [ push, pull_request ]

jobs:
  composer-validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 8.2 ]
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Validate
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
      - run: composer validate --strict --ansi

  composer-audit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        data: [
          { symfony: '5.4.*', php: 7.4 },
          { symfony: '5.4.*', php: 8.0 },
          { symfony: '5.4.*', php: 8.1 },
          { symfony: '5.4.*', php: 8.2 },

          { symfony: '6.4.*', php: 8.1 },
          { symfony: '6.4.*', php: 8.2 },

          { symfony: '7.1.*', php: 8.2 },

          { symfony: '7.2.*', php: 8.2 },
        ]

    steps:
      - uses: actions/checkout@v3.3.0

      - name: Install Infrastructure
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.data.php }}
          tools: composer:v2, flex
          coverage: none

      - name: Install Dependence and audit
        env:
          SYMFONY_REQUIRE: ${{ matrix.data.symfony }}
        uses: ramsey/composer-install@v2
        with:
          composer-options: --optimize-autoloader
          dependency-versions: "highest"
      - run: composer audit